"""empty message

Revision ID: 0877e2b39f78
Revises: 28fe45963cc6
Create Date: 2025-11-05 06:18:22.801422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0877e2b39f78'
down_revision: Union[str, Sequence[str], None] = '28fe45963cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_meeting_pair', 'usermeetings', ['user_uuid', 'meeting_uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_meeting_pair', 'usermeetings', type_='unique')
    # ### end Alembic commands ###
