"""empty message

Revision ID: 247379f6ebbb
Revises: 87f5e88c1d50
Create Date: 2025-11-03 03:50:21.447617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '247379f6ebbb'
down_revision: Union[str, Sequence[str], None] = '87f5e88c1d50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('rate', sa.Integer(), nullable=False))
    op.drop_column('evaluations', 'score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('evaluations', 'rate')
    # ### end Alembic commands ###
