"""empty message

Revision ID: 28fe45963cc6
Revises: e882b8342d71
Create Date: 2025-11-05 05:40:41.335540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28fe45963cc6'
down_revision: Union[str, Sequence[str], None] = 'e882b8342d71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usermeetings', sa.Column('meeting_uuid', sa.UUID(), nullable=False))
    op.add_column('usermeetings', sa.Column('user_uuid', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('usermeetings_user_id_fkey'), 'usermeetings', type_='foreignkey')
    op.drop_constraint(op.f('usermeetings_meeting_id_fkey'), 'usermeetings', type_='foreignkey')
    op.create_foreign_key(None, 'usermeetings', 'meetings', ['meeting_uuid'], ['uuid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'usermeetings', 'users', ['user_uuid'], ['uuid'], ondelete='CASCADE')
    op.drop_column('usermeetings', 'meeting_id')
    op.drop_column('usermeetings', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usermeetings', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('usermeetings', sa.Column('meeting_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'usermeetings', type_='foreignkey')
    op.drop_constraint(None, 'usermeetings', type_='foreignkey')
    op.create_foreign_key(op.f('usermeetings_meeting_id_fkey'), 'usermeetings', 'meetings', ['meeting_id'], ['uuid'], ondelete='CASCADE')
    op.create_foreign_key(op.f('usermeetings_user_id_fkey'), 'usermeetings', 'users', ['user_id'], ['uuid'], ondelete='CASCADE')
    op.drop_column('usermeetings', 'user_uuid')
    op.drop_column('usermeetings', 'meeting_uuid')
    # ### end Alembic commands ###
