"""empty message

Revision ID: 87f5e88c1d50
Revises: 9ccad8b8c0d7
Create Date: 2025-11-03 01:39:50.641377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87f5e88c1d50'
down_revision: Union[str, Sequence[str], None] = '9ccad8b8c0d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluations',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('performer', sa.UUID(), nullable=False),
    sa.Column('reviewer', sa.UUID(), nullable=False),
    sa.Column('task', sa.UUID(), nullable=False),
    sa.CheckConstraint('score >= 1 AND score <= 5', name='check_score_range'),
    sa.ForeignKeyConstraint(['performer'], ['users.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer'], ['users.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task'], ['tasks.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluations')
    # ### end Alembic commands ###
