"""empty message

Revision ID: f4fe795fc4fe
Revises: 
Create Date: 2025-11-13 23:26:55.261050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4fe795fc4fe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('teams',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('users',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('user', 'manager', 'admin', name='role'), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tasks',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('team', sa.UUID(), nullable=False),
    sa.Column('performer', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('waiting', 'in_progress', 'done', name='taskstatus'), server_default='waiting', nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('author', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['users.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performer'], ['users.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team'], ['teams.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('teamuser',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user', sa.UUID(), nullable=False),
    sa.Column('team', sa.UUID(), nullable=False),
    sa.Column('team_role', sa.Enum('employee', 'manager', name='teamrole'), nullable=False),
    sa.ForeignKeyConstraint(['team'], ['teams.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('usermeetings',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('meeting_uuid', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_uuid'], ['meetings.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('user_uuid', 'meeting_uuid', name='uq_user_meeting_pair')
    )
    op.create_table('comments',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('author', sa.UUID(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('task', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['users.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task'], ['tasks.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('evaluations',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=False),
    sa.Column('performer', sa.UUID(), nullable=False),
    sa.Column('reviewer', sa.UUID(), nullable=False),
    sa.Column('task', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rate >= 1 AND rate <= 5', name='check_rate_range'),
    sa.ForeignKeyConstraint(['performer'], ['users.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer'], ['users.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task'], ['tasks.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluations')
    op.drop_table('comments')
    op.drop_table('usermeetings')
    op.drop_table('teamuser')
    op.drop_table('tasks')
    op.drop_table('users')
    op.drop_table('teams')
    op.drop_table('meetings')
    # ### end Alembic commands ###
